---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - site.arthurbdiniz.com
    secretName: letsencrypt-prod
  rules:
  - host: site.arthurbdiniz.com
    http:
      paths:
      - backend:
          serviceName: site
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: site
spec:
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app: site
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
spec:
  selector:
    matchLabels:
      app: site
  replicas: 1
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
      - name: site
        image: arthurbdiniz/personal-site:latest
        ports:
        - containerPort: 4000